# Generated by Django 5.2.1 on 2025-06-24 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='sample_model',
            new_name='Posts',
        ),
    ]
